version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "UTC"
    ignore:
      - dependency-name: "pyrofork"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
