version: 2
updates:
  # Python requirements
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "19:49"
      timezone: "UTC"
    ignore:
      - dependency-name: "pyrofork"
    labels:
      - "dependencies"
      - "auto-update"
    reviewers:
      - "NBBotz"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
